/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module n_bit_adder(a, b, cin, sum, cout);
  wire [4:0] _0_;
  wire [4:0] _1_;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  input cin;
  wire cin;
  output cout;
  wire cout;
  wire [4:0] result_wire;
  output [3:0] sum;
  wire [3:0] sum;
  assign _0_ = { 1'h0, a } + { 1'h0, b };
  assign _1_ = _0_ + cin;
  assign result_wire = _1_;
  assign sum = result_wire[3:0];
  assign cout = result_wire[4];
endmodule

module n_bit_comprater(a, b, eq, gt, lt);
  wire _0_;
  wire _1_;
  wire _2_;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  output eq;
  wire eq;
  output gt;
  wire gt;
  output lt;
  wire lt;
  assign _0_ = a == b;
  assign _1_ = a > b;
  assign _2_ = a < b;
  assign eq = _0_;
  assign gt = _1_;
  assign lt = _2_;
endmodule

module n_bit_subtractor(a, b, borrow, diff);
  wire [4:0] _0_;
  wire [4:0] _1_;
  wire _2_;
  wire [3:0] _3_;
  input [3:0] a;
  wire [3:0] a;
  input [3:0] b;
  wire [3:0] b;
  output borrow;
  wire borrow;
  output [3:0] diff;
  wire [3:0] diff;
  wire [4:0] result_wire;
  assign _0_ = { 1'h0, a } + { 1'h0, _3_ };
  assign _1_ = _0_ + 1'h1;
  assign _2_ = ~ result_wire[4];
  assign _3_ = ~ b;
  assign result_wire = _1_;
  assign diff = result_wire[3:0];
  assign borrow = _2_;
endmodule
